export interface LanguageOption {
  code: string;
  label: string;
  locale: string;
  tier: "Tier 1" | "Tier 2" | "Tier 3";
  rtl?: boolean;
}

export interface CurrencyOption {
  code: string;
  label: string;
}

export const languages: LanguageOption[] = [
  { code: "zh-CN", label: "简体中文", locale: "zh-CN", tier: "Tier 1" },
  { code: "xerc", label: "xərcə", locale: "az-AZ", tier: "Tier 3" },
  { code: "ar", label: "العربية", locale: "ar", tier: "Tier 1", rtl: true },
  { code: "european-ar", label: "أوروبية", locale: "ar", tier: "Tier 3", rtl: true },
  { code: "az", label: "Azərbaycan", locale: "az-AZ", tier: "Tier 3" },
  { code: "bg", label: "български", locale: "bg-BG", tier: "Tier 3" },
  { code: "valjan", label: "ваљан", locale: "sr-RS", tier: "Tier 3" },
  { code: "cs", label: "Čeština", locale: "cs-CZ", tier: "Tier 3" },
  { code: "da", label: "Dansk", locale: "da-DK", tier: "Tier 3" },
  { code: "de-CH", label: "Deutsch (Schweiz)", locale: "de-CH", tier: "Tier 1" },
  { code: "el", label: "Ελληνικά", locale: "el-GR", tier: "Tier 3" },
  { code: "en", label: "English", locale: "en-US", tier: "Tier 1" },
  { code: "en-IN", label: "English (India)", locale: "en-IN", tier: "Tier 3" },
  { code: "en-AF", label: "English (Africa)", locale: "en-ZA", tier: "Tier 3" },
  { code: "en-KZ", label: "English (Kazakhstan)", locale: "en-KZ", tier: "Tier 3" },
  { code: "en-JP", label: "English (Japan)", locale: "en-JP", tier: "Tier 3" },
  { code: "en-TR", label: "English (Türkiye)", locale: "en-TR", tier: "Tier 3" },
  { code: "es-419", label: "Español (Latinoamérica)", locale: "es-419", tier: "Tier 1" },
  { code: "es-ES", label: "Español (España)", locale: "es-ES", tier: "Tier 2" },
  { code: "es-AR", label: "Español (Argentina)", locale: "es-AR", tier: "Tier 2" },
  { code: "fr", label: "Français", locale: "fr-FR", tier: "Tier 1" },
  { code: "fr-AF", label: "Français (Afrique)", locale: "fr-SN", tier: "Tier 2" },
  { code: "hr", label: "Hrvatski", locale: "hr-HR", tier: "Tier 3" },
  { code: "hu", label: "magyar nyelv", locale: "hu-HU", tier: "Tier 3" },
  { code: "id", label: "Bahasa Indonesia", locale: "id-ID", tier: "Tier 3" },
  { code: "it", label: "Italiano", locale: "it-IT", tier: "Tier 3" },
  { code: "kk", label: "Қазақша", locale: "kk-KZ", tier: "Tier 3" },
  { code: "talalya", label: "талалӱя", locale: "ru-RU", tier: "Tier 3" },
  { code: "ky", label: "Кыргыз", locale: "ky-KG", tier: "Tier 3" },
  { code: "aga", label: "ага", locale: "ru-RU", tier: "Tier 3" },
  { code: "lt", label: "Lietuvių", locale: "lt-LT", tier: "Tier 3" },
  { code: "lv", label: "latviešu valoda", locale: "lv-LV", tier: "Tier 3" },
  { code: "udgeh", label: "Үдгэһэх", locale: "ru-RU", tier: "Tier 3" },
  { code: "pl", label: "Polski", locale: "pl-PL", tier: "Tier 3" },
  { code: "pt-BR", label: "Português (Brasil)", locale: "pt-BR", tier: "Tier 1" },
  { code: "pt-PT", label: "Português (Portugal)", locale: "pt-PT", tier: "Tier 2" },
  { code: "pt-AO", label: "Português (Angola)", locale: "pt-AO", tier: "Tier 2" },
  { code: "ro", label: "Română", locale: "ro-RO", tier: "Tier 3" },
  { code: "ru", label: "Русский", locale: "ru-RU", tier: "Tier 1" },
  { code: "ru-KZ", label: "Русский (Казахстан)", locale: "ru-KZ", tier: "Tier 2" },
  { code: "booch", label: "Боочч", locale: "ru-RU", tier: "Tier 3" },
  { code: "sk", label: "Slovenčina", locale: "sk-SK", tier: "Tier 3" },
  { code: "sl", label: "Slovenščina", locale: "sl-SI", tier: "Tier 3" },
  { code: "sv", label: "svenska", locale: "sv-SE", tier: "Tier 3" },
  { code: "uk", label: "Українська", locale: "uk-UA", tier: "Tier 3" },
  { code: "uz", label: "O‘zbekcha", locale: "uz-UZ", tier: "Tier 3" },
  { code: "vi", label: "Tiếng Việt", locale: "vi-VN", tier: "Tier 3" },
  { code: "zh-TW", label: "繁體中文", locale: "zh-TW", tier: "Tier 1" }
];

export const currencies: CurrencyOption[] = [
  { code: "CNY", label: "人民币" },
  { code: "USD", label: "美元" },
  { code: "EUR", label: "欧元" },
  { code: "AED", label: "UAE dirham" },
  { code: "ARS", label: "Argentine Peso" },
  { code: "AUD", label: "Australian Dollar" },
  { code: "AZN", label: "Azerbaijan Manat" },
  { code: "BDT", label: "Bangladesh Taka" },
  { code: "BGN", label: "Bulgarian Lev" },
  { code: "BHD", label: "Bahraini Dinar" },
  { code: "BOB", label: "Bolivian Boliviano" },
  { code: "BRL", label: "Brazilian Real" },
  { code: "CAD", label: "Canadian Dollar" },
  { code: "CHF", label: "Swiss Franc" },
  { code: "CLP", label: "Chilean Peso" },
  { code: "COP", label: "Colombian Peso" },
  { code: "CZK", label: "Czech Koruna" },
  { code: "DKK", label: "Danish Krone" },
  { code: "EGP", label: "Egyptian Pound" },
  { code: "GBP", label: "Pound Sterling" },
  { code: "HKD", label: "Hong Kong Dollar" },
  { code: "HRK", label: "Croatian Kuna" },
  { code: "HUF", label: "Hungarian Forint" },
  { code: "IDR", label: "Indonesian Rupiah" },
  { code: "INR", label: "Indian Rupee" },
  { code: "JPY", label: "Japanese Yen" },
  { code: "KES", label: "Kenyan Shilling" },
  { code: "KWD", label: "Kuwaiti Dinar" },
  { code: "KZT", label: "Kazakhstan Tenge" },
  { code: "MAD", label: "Moroccan Dirham" },
  { code: "MNT", label: "Mongolian Tugrik" },
  { code: "MXN", label: "Mexican Peso" },
  { code: "NZD", label: "New Zealand Dollar" },
  { code: "OMR", label: "Omani Rial" },
  { code: "PEN", label: "Nuevo Sol" },
  { code: "PHP", label: "Philippine Peso" },
  { code: "PKR", label: "Pakistani Rupee" },
  { code: "PLN", label: "Polish Zloty" },
  { code: "QAR", label: "Qatari Riyal" },
  { code: "RON", label: "Romanian Leu" },
  { code: "RUB", label: "Russian Ruble" },
  { code: "SAR", label: "Saudi Riyal" },
  { code: "SEK", label: "Swedish Krona" },
  { code: "THB", label: "Thai Baht" },
  { code: "TRY", label: "Turkish Lira" },
  { code: "TWD", label: "New Taiwan dollar" },
  { code: "UAH", label: "Ukrainian Hryvnia" },
  { code: "UGX", label: "Uganda Shilling" },
  { code: "UZS", label: "Uzbekistani Sum" },
  { code: "VES", label: "Venezuelan Bolivar" },
  { code: "VND", label: "Vietnamese Dong" },
  { code: "ZAR", label: "South African Rand" }
];

type Dict = Record<string, string>;

const en: Dict = {
  appTagline: "Institutional Digital Asset Gateway",
  workspaceSearch: "Workspace Search",
  searchPlaceholder: "Search signals, accounts, symbols, logs",
  displayCurrency: "Display Currency",
  language: "Language",
  density: "Density",
  fontScale: "Font Scale",
  motion: "Motion",
  standard: "Standard",
  compact: "Compact",
  small: "Small",
  default: "Default",
  large: "Large",
  full: "Full",
  reduced: "Reduced",
  controls: "Operational controls and live execution telemetry.",
  runtime: "Runtime",
  performance: "Performance",
  signals: "Signals",
  copyTrades: "Copy Routing",
  apiRegistry: "API Registry",
  studio: "Studio",
  logs: "Audit Logs",
  positions: "Equity List",
  refresh: "Refresh",
  addSignal: "Add Signal",
  addApi: "Add API Account",
  addCopyTrade: "Add Copy Trade",
  sync: "Sync",
  latest: "Latest",
  apply: "Apply",
  save: "Save",
  delete: "Delete",
  cancel: "Cancel",
  build: "Build",
  edit: "Edit",
  validate: "Validate",
  test: "Test",
  createRoute: "Create Route",
  createSignal: "Create Signal",
  createApi: "Create API Account",
  generatedCommand: "Generated Command",
  lastExecution: "Last Execution Response",
  liveQueue: "Live Execution Queue",
  validationReasons: "Validation Reasons",
  exact: "1:1 Exact",
  scale: "Scale",
  notes: "Operator Notes",
  status: "Status",
  signalSources: "Signal Sources",
  apiAccounts: "API Accounts",
  readiness: "Readiness",
  connected: "Connected",
  offline: "Offline",
  selectCopyTrade: "Select a copy trade to edit route configuration.",
  securityTitle: "Credential Operating Rules",
  tradeOnly: "Enable trade permissions only.",
  noWithdrawals: "Never enable withdrawals.",
  whitelist: "Use recommended IP whitelist where supported.",
  okxPassphrase: "OKX requires API passphrase.",
  encrypted: "Credentials are stored encrypted at rest.",
  displayConverted: "Display currency converted",
  noData: "No data available",
  follower: "Follower",
  signal: "Signal",
  exchange: "Exchange",
  environment: "Environment",
  symbol: "Symbol",
  action: "Action",
  queue: "Queue",
  latency: "Latency",
  message: "Message",
  timestamp: "Timestamp",
  type: "Type",
  key: "Key",
  pnl: "PnL",
  exposure: "Exposure",
  leverage: "Leverage",
  freshness: "Freshness",
  source: "Source",
  captured: "Captured",
  yes: "Yes",
  no: "No",
  loading: "Loading..."
};

const zhCN: Dict = {
  appTagline: "机构级数字资产控制网关",
  workspaceSearch: "工作区搜索",
  searchPlaceholder: "搜索信号、账户、交易对、日志",
  displayCurrency: "显示币种",
  language: "语言",
  density: "密度",
  fontScale: "字号",
  motion: "动效",
  standard: "标准",
  compact: "紧凑",
  small: "小",
  default: "默认",
  large: "大",
  full: "完整",
  reduced: "减少",
  controls: "运行控制与实时执行遥测。",
  runtime: "运行",
  performance: "绩效",
  signals: "信号",
  copyTrades: "跟单路由",
  apiRegistry: "API 注册",
  studio: "执行工作台",
  logs: "审计日志",
  positions: "权益列表",
  refresh: "刷新",
  addSignal: "新增信号",
  addApi: "新增 API 账户",
  addCopyTrade: "新增跟单路由",
  sync: "同步",
  latest: "最新",
  apply: "应用",
  save: "保存",
  delete: "删除",
  cancel: "取消",
  build: "构建",
  edit: "编辑",
  validate: "校验",
  test: "测试",
  createRoute: "创建路由",
  createSignal: "创建信号",
  createApi: "创建 API 账户",
  generatedCommand: "生成命令",
  lastExecution: "最近执行响应",
  liveQueue: "实时执行队列",
  validationReasons: "校验原因",
  exact: "1:1 精确复制",
  scale: "比例复制",
  notes: "操作备注",
  status: "状态",
  signalSources: "信号源",
  apiAccounts: "API 账户",
  readiness: "就绪状态",
  connected: "已连接",
  offline: "离线",
  selectCopyTrade: "选择一条跟单路由进行配置。",
  securityTitle: "凭证使用规则",
  tradeOnly: "仅开启交易权限。",
  noWithdrawals: "不要开启提现权限。",
  whitelist: "支持时请配置 IP 白名单。",
  okxPassphrase: "OKX 需要 API Passphrase。",
  encrypted: "凭证以加密方式存储。",
  displayConverted: "显示币种已换算",
  noData: "暂无数据",
  follower: "子账户",
  signal: "信号",
  exchange: "交易所",
  environment: "环境",
  symbol: "交易对",
  action: "动作",
  queue: "队列",
  latency: "延迟",
  message: "消息",
  timestamp: "时间",
  type: "类型",
  key: "键",
  pnl: "盈亏",
  exposure: "敞口",
  leverage: "杠杆",
  freshness: "新鲜度",
  source: "来源",
  captured: "采集时间",
  yes: "是",
  no: "否",
  loading: "加载中..."
};

const zhTW: Dict = {
  appTagline: "機構級數位資產控制閘道",
  workspaceSearch: "工作區搜尋",
  searchPlaceholder: "搜尋信號、帳戶、交易對、日誌",
  displayCurrency: "顯示幣種",
  language: "語言",
  signals: "信號",
  copyTrades: "跟單路由",
  apiRegistry: "API 註冊",
  studio: "執行工作台",
  logs: "審計日誌",
  positions: "權益列表",
  refresh: "刷新",
  addSignal: "新增信號",
  addApi: "新增 API 帳戶",
  addCopyTrade: "新增跟單路由",
  save: "儲存",
  delete: "刪除",
  cancel: "取消",
  build: "構建",
  edit: "編輯",
  validate: "校驗",
  exact: "1:1 精確複製",
  scale: "比例複製",
  connected: "已連線",
  offline: "離線",
  noData: "暫無資料"
};

const ar: Dict = {
  appTagline: "بوابة مؤسسية للأصول الرقمية",
  workspaceSearch: "بحث مساحة العمل",
  searchPlaceholder: "ابحث في الإشارات والحسابات والرموز والسجلات",
  displayCurrency: "عملة العرض",
  language: "اللغة",
  signals: "الإشارات",
  copyTrades: "مسارات النسخ",
  apiRegistry: "سجل API",
  studio: "استوديو التنفيذ",
  logs: "سجلات التدقيق",
  positions: "قائمة الأصول",
  refresh: "تحديث",
  addSignal: "إضافة إشارة",
  addApi: "إضافة حساب API",
  addCopyTrade: "إضافة مسار نسخ",
  save: "حفظ",
  delete: "حذف",
  cancel: "إلغاء",
  build: "إنشاء",
  edit: "تعديل",
  validate: "تحقق",
  exact: "نسخ دقيق 1:1",
  scale: "نسخ بنسبة",
  connected: "متصل",
  offline: "غير متصل",
  noData: "لا توجد بيانات"
};

const ru: Dict = {
  appTagline: "Институциональный шлюз цифровых активов",
  workspaceSearch: "Поиск по рабочей области",
  searchPlaceholder: "Искать сигналы, счета, символы и журналы",
  displayCurrency: "Валюта отображения",
  language: "Язык",
  signals: "Сигналы",
  copyTrades: "Маршруты копирования",
  apiRegistry: "Реестр API",
  studio: "Панель исполнения",
  logs: "Журналы аудита",
  positions: "Список капитала",
  refresh: "Обновить",
  addSignal: "Добавить сигнал",
  addApi: "Добавить API счет",
  addCopyTrade: "Добавить маршрут",
  save: "Сохранить",
  delete: "Удалить",
  cancel: "Отмена",
  build: "Собрать",
  edit: "Изменить",
  validate: "Проверить",
  exact: "Точное 1:1",
  scale: "Масштаб",
  connected: "Подключено",
  offline: "Офлайн",
  noData: "Нет данных"
};

const es419: Dict = {
  appTagline: "Puerta institucional de activos digitales",
  workspaceSearch: "Búsqueda del espacio",
  searchPlaceholder: "Buscar señales, cuentas, símbolos y registros",
  displayCurrency: "Moneda de visualización",
  language: "Idioma",
  signals: "Señales",
  copyTrades: "Rutas de copia",
  apiRegistry: "Registro API",
  studio: "Estudio de ejecución",
  logs: "Registros de auditoría",
  positions: "Lista de capital",
  refresh: "Actualizar",
  addSignal: "Agregar señal",
  addApi: "Agregar cuenta API",
  addCopyTrade: "Agregar ruta",
  save: "Guardar",
  delete: "Eliminar",
  cancel: "Cancelar",
  build: "Construir",
  edit: "Editar",
  validate: "Validar",
  exact: "Copia exacta 1:1",
  scale: "Escala",
  connected: "Conectado",
  offline: "Sin conexión",
  noData: "Sin datos"
};

const fr: Dict = {
  appTagline: "Passerelle institutionnelle d’actifs numériques",
  workspaceSearch: "Recherche d’espace",
  searchPlaceholder: "Rechercher signaux, comptes, symboles et journaux",
  displayCurrency: "Devise d’affichage",
  language: "Langue",
  signals: "Signaux",
  copyTrades: "Routage de copie",
  apiRegistry: "Registre API",
  studio: "Studio d’exécution",
  logs: "Journaux d’audit",
  positions: "Liste des fonds",
  refresh: "Actualiser",
  addSignal: "Ajouter un signal",
  addApi: "Ajouter un compte API",
  addCopyTrade: "Ajouter une route",
  save: "Enregistrer",
  delete: "Supprimer",
  cancel: "Annuler",
  build: "Construire",
  edit: "Modifier",
  validate: "Valider",
  exact: "Copie exacte 1:1",
  scale: "Échelle",
  connected: "Connecté",
  offline: "Hors ligne",
  noData: "Aucune donnée"
};

const deCH: Dict = {
  appTagline: "Institutionelles Gateway für digitale Vermögenswerte",
  workspaceSearch: "Arbeitsbereichssuche",
  searchPlaceholder: "Signale, Konten, Symbole und Logs suchen",
  displayCurrency: "Anzeigewährung",
  language: "Sprache",
  signals: "Signale",
  copyTrades: "Copy Routing",
  apiRegistry: "API-Register",
  studio: "Ausführungsstudio",
  logs: "Audit-Logs",
  positions: "Equity-Liste",
  refresh: "Aktualisieren",
  addSignal: "Signal hinzufügen",
  addApi: "API-Konto hinzufügen",
  addCopyTrade: "Route hinzufügen",
  save: "Speichern",
  delete: "Löschen",
  cancel: "Abbrechen",
  build: "Erstellen",
  edit: "Bearbeiten",
  validate: "Validieren",
  exact: "Exakt 1:1",
  scale: "Skalieren",
  connected: "Verbunden",
  offline: "Offline",
  noData: "Keine Daten"
};

const ptBR: Dict = {
  appTagline: "Gateway institucional de ativos digitais",
  workspaceSearch: "Busca do workspace",
  searchPlaceholder: "Buscar sinais, contas, símbolos e logs",
  displayCurrency: "Moeda de exibição",
  language: "Idioma",
  signals: "Sinais",
  copyTrades: "Rotas de cópia",
  apiRegistry: "Registro API",
  studio: "Estúdio de execução",
  logs: "Logs de auditoria",
  positions: "Lista de patrimônio",
  refresh: "Atualizar",
  addSignal: "Adicionar sinal",
  addApi: "Adicionar conta API",
  addCopyTrade: "Adicionar rota",
  save: "Salvar",
  delete: "Excluir",
  cancel: "Cancelar",
  build: "Construir",
  edit: "Editar",
  validate: "Validar",
  exact: "Cópia exata 1:1",
  scale: "Escala",
  connected: "Conectado",
  offline: "Offline",
  noData: "Sem dados"
};

export const dictionaries: Record<string, Dict> = {
  en,
  "zh-CN": { ...en, ...zhCN },
  "zh-TW": { ...en, ...zhTW },
  ar: { ...en, ...ar },
  ru: { ...en, ...ru },
  "es-419": { ...en, ...es419 },
  fr: { ...en, ...fr },
  "de-CH": { ...en, ...deCH },
  "pt-BR": { ...en, ...ptBR }
};

export function t(language: string, key: string): string {
  return dictionaries[language]?.[key] ?? en[key] ?? key;
}

export function getLanguage(languageCode: string): LanguageOption {
  return languages.find((item) => item.code === languageCode) ?? languages.find((item) => item.code === "en")!;
}
